### PR TITLE
Make compatible with ruby 3.0.0

### PR DESCRIPTION
**Pull request by werthen**
Ruby 3 dropped support of passing a Hash for keyword arguments. Using a double splat fixes this problem. This should still be compatible on older Ruby versions as well.

### CODE REVIEW

**Comment by matthutchinson** [comment]
Can you cut a release for this?

**Comment by werthen** [comment]
@matthutchinson Right now I have it forked so you can add it to a Gemfile as follows:

```
gem 'words_counted', git: 'https://github.com/werthen/words_counted'
```

I might package this fork for convenience at a later time if the maintainer here doesn't respond.

**Comment by seuros** [comment]
@abitdodgy any release planned ?

**Comment by abitdodgy** [comment]
Hey everyone. I'll do a new release this weekend.

**Comment by werthen** [comment]
@abitdodgy Thanks a lot! could you also make a release on rubygems.org? that way we can use it in our gemfiles as well.

**Pull request merged**
