### PR TITLE
Filter can be array or lambda.

### PR DESCRIPTION
**Pull request by abitdodgy**

### CODE REVIEW

**Comment by abitdodgy** [comment]
Hi @wconrad! I'm bringing this back from the dead as I do some refactoring. It got me thinking about the `filter_proc` method, most of which you wrote.

```ruby
def filter_proc(filter)
      if filter.respond_to?(:to_a)
        filter_procs = Array(filter).map(&method(:filter_proc))
        ->(word) {
          filter_procs.any? { |p| p.call(word) }
        }
      elsif filter.respond_to?(:to_str)
        f = filter.split.collect { |word| word.downcase } # <---- THIS LINE HERE
        ->(w) { f.include?(w.downcase) }
      elsif Regexp.try_convert(filter)
        filter = Regexp.try_convert(filter)
        Proc.new { |w| w =~ filter }
      elsif filter.respond_to?(:to_proc)
        filter.to_proc
      else
        raise ArgumentError, "Incorrect filter type"
      end
    end
```

I understand whats going on here, mostly because I went back and reread your code review (it makes so much sense now that I actually have some good experience under my belt).

There is one line I want to enquire about.

```ruby
filter_procs = Array(filter).map(&method(:filter_proc))
```

If I understand this correctly, we're using recursion? If an array is passed, then this line will run and iterate over the array. It will call the method `filter_proc` for each item, passing in the item as an argument. The time the other conditions should catch it, be it a string, a regexp, or a proc. The return value will always be a callable object, which bubbles back up the stack. Does this make sense? This is pretty genius because you can pass in an array of any combination of filters in an array.

**Comment by wconrad** [comment]
Yes, you've got it: it is recursive.  The only twist is that the recursion does not happen at the time filter_proc is called.  It happens, later, at the time that the lambda returned by filter_proc is called.

The "pass in an array of any combination of filters" is exactly what the code means to achieve, so you've interpreted it exactly right.

**Comment by wconrad** [comment]
No, wait, i was wrong.  The recursion _does_ happen at the time the method is called.

**Comment by abitdodgy** [comment]
@wconrad thanks! That makes sense. I should write some tests and document this feature. :smile:

**Comment by abitdodgy** [comment]
I forgot to ask one last thing. 

```
def filter_proc(filter)
  if filter.respond_to?(:to_a)
    # ...
  elsif regexp_filter = Regexp.try_convert(filter)
    Proc.new { |word| word =~ regexp_filter }
  else
  # ...
```

In the case of a `regexp`, is a reason we're using a proc and not a lamba? In my tests `->(word) { word =~ regexp_filter }` words just as well.

**Pull request merged**
